name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: waytel/shop-app 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Définir le tag de l'image avec le SHA du commit
    - name: Set Docker Image Tag
      id: image_tag
      run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    # Étape 3 : Se connecter à Docker Hub
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Étape 4 : Construire et envoyer l'image Docker
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./api
        docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Étape 5 : Connexion à Azure avec le fichier de profil de publication
    - name: Login to Azure Web App
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    # Étape 6 : Déployer l'image Docker sur Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: shop-app-service
        slot-name: production
        images: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
