name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Installer Terraform et valider la configuration
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Initialize and Validate Terraform
      run: |
        terraform init
        terraform validate

    # Étape 3 : Se connecter à Docker Hub
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Étape 4 : Construire l'image Docker pour valider le Dockerfile
    - name: Build Docker Image
      run: |
        docker build -t waytel/shop-app:${{ github.event.pull_request.number }} ./api

